[rabbit]
protocol = "amqp"
hostname = "localhost"
port = "5672"
username = "guest"
password = "guest"
heartbeat = 60 # seconds
vhost = "/"
exchange = "hozon"
routingKey = "download"
queue = "downloadQueue"
prefetch = 1